# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: landing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='landing.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\027org.feuyeux.given.protoB\007LandingP\001'),
  serialized_pb=_b('\n\rlanding.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n\x0bTalkRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04meta\x18\x02 \x01(\t\"\x1a\n\tTalkChunk\x12\r\n\x05\x63hunk\x18\x03 \x01(\x0c\"<\n\x0cTalkResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x1c\n\x07results\x18\x02 \x03(\x0b\x32\x0b.TalkResult\"\x7f\n\nTalkResult\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ResultType\x12\x1f\n\x02kv\x18\x03 \x03(\x0b\x32\x13.TalkResult.KvEntry\x1a)\n\x07KvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*R\n\nResultType\x12\n\n\x06SEARCH\x10\x00\x12\x0c\n\x08\x41NALYSIS\x10\x01\x12\x0e\n\nSTATISTICS\x10\x02\x12\x0b\n\x07MONITOR\x10\x03\x12\r\n\tRECOMMEND\x10\x04\x32l\n\x0eLandingService\x12%\n\x04talk\x12\x0c.TalkRequest\x1a\r.TalkResponse\"\x00\x12\x33\n\ttalkChunk\x12\x16.google.protobuf.Empty\x1a\n.TalkChunk\"\x00\x30\x01\x42$\n\x17org.feuyeux.given.protoB\x07LandingP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_RESULTTYPE = _descriptor.EnumDescriptor(
  name='ResultType',
  full_name='ResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEARCH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANALYSIS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATISTICS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONITOR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECOMMEND', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=308,
  serialized_end=390,
)
_sym_db.RegisterEnumDescriptor(_RESULTTYPE)

ResultType = enum_type_wrapper.EnumTypeWrapper(_RESULTTYPE)
SEARCH = 0
ANALYSIS = 1
STATISTICS = 2
MONITOR = 3
RECOMMEND = 4



_TALKREQUEST = _descriptor.Descriptor(
  name='TalkRequest',
  full_name='TalkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='TalkRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='TalkRequest.meta', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=87,
)


_TALKCHUNK = _descriptor.Descriptor(
  name='TalkChunk',
  full_name='TalkChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='TalkChunk.chunk', index=0,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=115,
)


_TALKRESPONSE = _descriptor.Descriptor(
  name='TalkResponse',
  full_name='TalkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TalkResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='TalkResponse.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=177,
)


_TALKRESULT_KVENTRY = _descriptor.Descriptor(
  name='KvEntry',
  full_name='TalkResult.KvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TalkResult.KvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TalkResult.KvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=306,
)

_TALKRESULT = _descriptor.Descriptor(
  name='TalkResult',
  full_name='TalkResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TalkResult.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='TalkResult.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kv', full_name='TalkResult.kv', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TALKRESULT_KVENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=306,
)

_TALKRESPONSE.fields_by_name['results'].message_type = _TALKRESULT
_TALKRESULT_KVENTRY.containing_type = _TALKRESULT
_TALKRESULT.fields_by_name['type'].enum_type = _RESULTTYPE
_TALKRESULT.fields_by_name['kv'].message_type = _TALKRESULT_KVENTRY
DESCRIPTOR.message_types_by_name['TalkRequest'] = _TALKREQUEST
DESCRIPTOR.message_types_by_name['TalkChunk'] = _TALKCHUNK
DESCRIPTOR.message_types_by_name['TalkResponse'] = _TALKRESPONSE
DESCRIPTOR.message_types_by_name['TalkResult'] = _TALKRESULT
DESCRIPTOR.enum_types_by_name['ResultType'] = _RESULTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TalkRequest = _reflection.GeneratedProtocolMessageType('TalkRequest', (_message.Message,), dict(
  DESCRIPTOR = _TALKREQUEST,
  __module__ = 'landing_pb2'
  # @@protoc_insertion_point(class_scope:TalkRequest)
  ))
_sym_db.RegisterMessage(TalkRequest)

TalkChunk = _reflection.GeneratedProtocolMessageType('TalkChunk', (_message.Message,), dict(
  DESCRIPTOR = _TALKCHUNK,
  __module__ = 'landing_pb2'
  # @@protoc_insertion_point(class_scope:TalkChunk)
  ))
_sym_db.RegisterMessage(TalkChunk)

TalkResponse = _reflection.GeneratedProtocolMessageType('TalkResponse', (_message.Message,), dict(
  DESCRIPTOR = _TALKRESPONSE,
  __module__ = 'landing_pb2'
  # @@protoc_insertion_point(class_scope:TalkResponse)
  ))
_sym_db.RegisterMessage(TalkResponse)

TalkResult = _reflection.GeneratedProtocolMessageType('TalkResult', (_message.Message,), dict(

  KvEntry = _reflection.GeneratedProtocolMessageType('KvEntry', (_message.Message,), dict(
    DESCRIPTOR = _TALKRESULT_KVENTRY,
    __module__ = 'landing_pb2'
    # @@protoc_insertion_point(class_scope:TalkResult.KvEntry)
    ))
  ,
  DESCRIPTOR = _TALKRESULT,
  __module__ = 'landing_pb2'
  # @@protoc_insertion_point(class_scope:TalkResult)
  ))
_sym_db.RegisterMessage(TalkResult)
_sym_db.RegisterMessage(TalkResult.KvEntry)


DESCRIPTOR._options = None
_TALKRESULT_KVENTRY._options = None

_LANDINGSERVICE = _descriptor.ServiceDescriptor(
  name='LandingService',
  full_name='LandingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=392,
  serialized_end=500,
  methods=[
  _descriptor.MethodDescriptor(
    name='talk',
    full_name='LandingService.talk',
    index=0,
    containing_service=None,
    input_type=_TALKREQUEST,
    output_type=_TALKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='talkChunk',
    full_name='LandingService.talkChunk',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TALKCHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LANDINGSERVICE)

DESCRIPTOR.services_by_name['LandingService'] = _LANDINGSERVICE

# @@protoc_insertion_point(module_scope)
